version: "3"
services:
  ckb:
    image: nervos/ckb:v0.114.0
    entrypoint: ["/bin/bash","-c"]
    container_name: ckb-mainnet
    restart: always
    ports:
      - 8314:8114
    volumes:
      - ./ckb-data:/var/lib/ckb
    command:
    - |
      set -ex
      cd /var/lib/ckb
      ckb init --chain mainnet || true
      ckb migrate --force
      ckb run
